// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwF99DY71t2TK2o5EKZSZs8pYNuQvKauQ',
    appId: '1:476448551388:web:37f300f352d0d45abc5f19',
    messagingSenderId: '476448551388',
    projectId: 'login-ui-4cdba',
    authDomain: 'login-ui-4cdba.firebaseapp.com',
    storageBucket: 'login-ui-4cdba.appspot.com',
    measurementId: 'G-4YEVP071Y9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABVPaDWs3ISVF7VkYwsviMXvr5vIQGqNU',
    appId: '1:476448551388:android:4c2f29d208ccf41fbc5f19',
    messagingSenderId: '476448551388',
    projectId: 'login-ui-4cdba',
    storageBucket: 'login-ui-4cdba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCEvE1EwitBoRFKQapYz9jJU5ent55yM4',
    appId: '1:476448551388:ios:0857435c951f4e79bc5f19',
    messagingSenderId: '476448551388',
    projectId: 'login-ui-4cdba',
    storageBucket: 'login-ui-4cdba.appspot.com',
    iosBundleId: 'com.example.uiLoginTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCEvE1EwitBoRFKQapYz9jJU5ent55yM4',
    appId: '1:476448551388:ios:4b3ec0e12f655f8cbc5f19',
    messagingSenderId: '476448551388',
    projectId: 'login-ui-4cdba',
    storageBucket: 'login-ui-4cdba.appspot.com',
    iosBundleId: 'com.example.uiLoginTest.RunnerTests',
  );
}
